/// This file contains utilities used by the Dart code generated by the
/// 🍭 Candy compiler.
///
/// It is simply copied into every output directory and can then imported from
/// every generated file.
library candy_dart_utils;

import 'package:meta/meta.dart';

export 'package:characters/characters.dart' show StringCharacters;

/// Used with `throw` and `catch` to implement non-local returns.
@sealed
class NonLocalReturnException {
  const NonLocalReturnException(this.scope, this.value);

  final Object scope;
  final dynamic value;
}

/// This is the base class for all generated `Value$` classes.
abstract class Value {
  InlineType get inlineType;
}

/// This is the base class for all generated `InlineType$` classes.
abstract class InlineType {
  bool equals(InlineType other);
}

// Type declarations

@sealed
class Value$Type implements Value {
  const Value$Type(this.inlineType, this.value);

  @override
  final InlineType inlineType;

  final Value value;
}

abstract class InlineType$Type implements InlineType {}

// Trait declarations

abstract class Value$Trait implements Value {}

abstract class InlineType$Trait implements InlineType {}
}

// Functions

abstract class Value$Function implements Value {}

abstract class InlineType$Function implements InlineType {}

// Structs

abstract class Value$Struct implements Value {}

abstract class InlineType$Struct implements InlineType {}

// Enums

abstract class Value$Enum implements Value {}

abstract class InlineType$Enum implements InlineType {}
