/// This file contains utilities used by the Dart code generated by the
/// 🍭 Candy compiler.
///
/// It is simply copied into every output directory and can then imported from
/// every generated file.
library candy_dart_utils;

import 'package:meta/meta.dart';

export 'package:characters/characters.dart' show StringCharacters;

/// Used with `throw` and `catch` to implement non-local returns.
@sealed
class NonLocalReturnException {
  const NonLocalReturnException(this.scope, this.value);

  final Object scope;
  final dynamic value;
}

/// This is the base class for all Candy values.
abstract class CandyValue {
  const CandyValue();
}

/// This is the base class for all generated `$Static` classes.
abstract class CandyInlineType {
  const CandyInlineType();
}

abstract class CandyTypeInlineType {
  const CandyTypeInlineType();
}
abstract class CandyTraitInlineType {
  const CandyTraitInlineType();
}
