/// This file contains utilities used by the Dart code generated by the
/// 🍭 Candy compiler.
///
/// It is simply copied into every output directory and can then imported from
/// every generated file.
library candy_dart_utils;

import 'package:meta/meta.dart';

export 'package:characters/characters.dart' show StringCharacters;

/// Used with `throw` and `catch` to implement non-local returns.
@sealed
class NonLocalReturnException {
  const NonLocalReturnException(this.scope, this.value);

  final Object scope;
  final dynamic value;
}
